apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGZ6ZzdkYmVt
  CLOUDINARY_KEY: ODk0Nzk5Mzg0NzUxODkx
  CLOUDINARY_SECRET: TXdBT18zUWg3LUh5VDRWZmJVb0tfbWpscUlz
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljbUZuYUhWeVlXMDVPU0lzSW1FaU9pSmpiVzFwTUhka09ITXdiSE5rTW5KeE1HYzBjMkp3Y2pJeEluMC5fX3JUaUhtMzZ3bjM0UnlxOWc0TkNB
  DB_URL: bW9uZ29kYitzcnY6Ly9yb290OnJvb3RAY2x1c3RlcjAueXVha3UzOC5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
